
Lt11=4.8;Lt12=1.2;Lt13=3.6;Lt14=1.2;Lt15=1.2;Lt16=4.134; %çekici uzunluklar
Lt21=4;Lt22=0.685;Lt23=0.7;Lt24=1.2;Lt25=1.2;Lt26=6.973; %römork uzunluklarý
kt1=155800;ct1=200000; %baðlama noktasý parametreleri
kt2=155800;kt3=2000000;ct2=44506;ct3=0; %römork sol arka
kt4=155800;kt5=2000000;ct4=44506;ct5=0; %römork sað arka
kt6=155800;kt7=2000000;ct6=44506;ct7=0; %römork sol ön
kt8=155800;kt9=2000000;ct8=44506;ct9=0; %römork sað ön
kt10=967430;kt11=2000000;ct10=27627;ct11=0; %çekici sol arka
kt12=967430;kt13=2000000;ct12=27627;ct13=0; %çekici sað arka
kt14=967430;kt15=2000000;ct14=27627;ct15=0; %çekici sol orta
kt16=967430;kt17=2000000;ct16=27627;ct17=0; %çekici sað orta
kt18=300000;kt19=847000;ct18=10000;ct19=0; %çekici sol ön
kt20=300000;kt21=847000;ct20=10000;ct21=0; %çekici sað ön
mt1=9785;mt2=26000; %çekici ve römork kütleleri
mt3=270;mt4=270;mt5=270;mt6=270; %römork süspansiyon kütleleri
mt7=520;mt8=520;mt9=520;mt10=520;mt11=270;mt12=270; %çekici süspansiyon kütleleri
Jt11=18311; %çekici kafa vurma kütle atalet momenti
Jt12=((Jt11-mt11*(Lt12-(Lt11+Lt12)/2)^2)/((Lt11+Lt12)/2)^2)*Lt14^2; %çekici yalpa kütle atalet momenti
Jt21=251900; %römork kafa vurma kütle atalet momenti
Jt22=((Jt21-mt2*(Lt22-(Lt21+Lt22)/2)^2)/((Lt21+Lt22)/2)^2)*Lt24^2; %römork yalpa kütle atalet momenti
Jt3=3300; %römork sol teker çifti atalet momenti
Jt4=3300; %römork sað teker çifti atalet momenti
Vt=60/3.6; %araç hýzý 60 km/h
dy=0.007;
wt=Vt/dy;






Mt=[mt1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;
       0 mt2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;
       0 0 mt3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0;
       0 0 0 mt4 0 0 0 0 0 0 0 0 0 0 0 0 0 0;
       0 0 0 0 mt5 0 0 0 0 0 0 0 0 0 0 0 0 0;
       0 0 0 0 0 mt6 0 0 0 0 0 0 0 0 0 0 0 0;
       0 0 0 0 0 0 mt7 0 0 0 0 0 0 0 0 0 0 0;
       0 0 0 0 0 0 0 mt8 0 0 0 0 0 0 0 0 0 0;
       0 0 0 0 0 0 0 0 mt9 0 0 0 0 0 0 0 0 0;
       0 0 0 0 0 0 0 0 0 mt10 0 0 0 0 0 0 0 0;
       0 0 0 0 0 0 0 0 0 0 mt11 0 0 0 0 0 0 0;
       0 0 0 0 0 0 0 0 0 0 0 mt12 0 0 0 0 0 0;
       0 0 0 0 0 0 0 0 0 0 0 0 Jt11 0 0 0 0 0;
       0 0 0 0 0 0 0 0 0 0 0 0 0 Jt12 0 0 0 0;
       0 0 0 0 0 0 0 0 0 0 0 0 0 0 Jt21 0 0 0;
       0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 Jt22 0 0;
       0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 Jt3 0;
       0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 Jt4];




Kt=[(kt1+kt10+kt12+kt14+kt16+kt18+kt20 )                                                                      -kt1                                                                            0                               0                               0                                 0                            -kt10                   -kt12                   -kt14                   -kt16                   -kt18                   -kt20                        (kt1*Lt16+kt10*Lt11+kt12*Lt11+kt14*Lt13+kt16*Lt13-kt18*Lt12-kt20*Lt12 )                                               (kt10*Lt14-kt12*Lt15+kt14*Lt14-kt16*Lt15+kt18*Lt14-kt20*Lt15 )                                                                kt1*Lt26                                                                                                                             0                                                                                                                                                0                                                                             0                                                             ;
      -(kt1 )                                                                                                                                        (kt1+kt2+kt4+kt6+kt8 )                                  -kt2                 -kt4                 -kt6                   -kt8                        0                                  0                                    0                                    0                                     0                                    0                                    (-kt1*Lt16 )                                                                                                                                                                                    0                                                                                                                                                                                                (-kt1*Lt26+(kt2+kt4+kt6+kt8 )*Lt21 )                                                     (kt2*Lt24-kt4*Lt25+kt6*Lt24-kt8*Lt25 )                                                       (kt2*Lt23-kt6*Lt22 )                                          (kt4*Lt23-kt8*Lt22 )                       ;
                0                                                                                                                                             -kt2                                                                             (kt2+kt3 )       0                               0                                 0                                   0                                  0                                    0                                    0                                     0                                    0                                              0                                                                                                                                                                                                      0                                                                                                                                                                                                -kt2*Lt21                                                                                                              -kt2*Lt24                                                                                                                     -kt2*Lt23                                                                        0                                                             ;
                0                                                                                                                                             -kt4                                                                             0                              (kt4+kt5 )        0                                 0                                   0                                  0                                    0                                    0                                     0                                    0                                              0                                                                                                                                                                                                      0                                                                                                                                                                                                -kt4*Lt21                                                                                                               kt4*Lt25                                                                                                                                    0                                                                       -kt4*Lt23                                              ;                             
                0                                                                                                                                             -kt6                                                                             0                               0                              (kt6+kt7 )          0                                   0                                  0                                    0                                    0                                     0                                    0                                              0                                                                                                                                                                                                      0                                                                                                                                                                                                -kt6*Lt21                                                                                                               -kt6*Lt24                                                                                                                    kt6*Lt22                                                                       0                                                             ;
                0                                                                                                                                             -kt8                                                                             0                               0                               0                                 (kt8+kt9 )           0                                  0                                    0                                    0                                     0                                    0                                              0                                                                                                                                                                                                      0                                                                                                                                                                                                -kt8*Lt21                                                                                                               kt8*Lt25                                                                                                                                    0                                                                       kt8*Lt22                                            ;
    -kt10                                                                                                                                                0                                                                                    0                               0                               0                                 0                             (kt10+kt11 )            0                                    0                                    0                                     0                                    0                                    -kt10*Lt11                                                                                                                                                                                 -kt10*Lt14                                                                                                                                                                                    0                                                                                                                                             0                                                                                                                                              0                                                                              0                                                             ;
    -kt12                                                                                                                                                0                                                                                    0                               0                               0                                 0                                   0                              (kt12+kt13 )            0                                    0                                     0                                    0                                    -kt12*Lt11                                                                                                                                                                                kt12*Lt15                                                                                                                                                                                    0                                                                                                                                             0                                                                                                                                              0                                                                              0                                                             ;
    -kt14                                                                                                                                                0                                                                                    0                               0                               0                                 0                                   0                                  0                                (kt14+kt15 )            0                                     0                                    0                                    -kt14*Lt13                                                                                                                                                                                 -kt14*Lt14                                                                                                                                                                                    0                                                                                                                                             0                                                                                                                                              0                                                                              0                                                             ;
    -kt16                                                                                                                                                0                                                                                    0                               0                               0                                 0                                   0                                  0                                    0                              (kt16+kt17 )             0                                    0                                    -kt16*Lt13                                                                                                                                                                                kt16*Lt15                                                                                                                                                                                    0                                                                                                                                              0                                                                                                                                             0                                                                              0                                                             ;    
    -kt18                                                                                                                                                0                                                                                    0                               0                               0                                 0                                   0                                  0                                    0                                    0                              (kt18+kt19 )             0                                    kt18*Lt12                                                                                                                                                                               -kt18*Lt14                                                                                                                                                                                     0                                                                                                                                              0                                                                                                                                             0                                                                              0                                                            ;                      
    -kt20                                                                                                                                                0                                                                                    0                               0                               0                                 0                                   0                                  0                                    0                                    0                                     0                               (kt20+kt21 )           kt20*Lt12                                                                                                                                                                               kt20*Lt15                                                                                                                                                                                    0                                                                                                                                              0                                                                                                                                             0                                                                               0                                                             ;
      (kt1*Lt16+kt10*Lt11+kt12*Lt11+kt14*Lt13+kt16*Lt13-kt18*Lt12-kt20*Lt12 )  -kt1*Lt16                                                                0                               0                               0                                 0                             -kt10*Lt11       -kt12*Lt11          -kt14*Lt13        -kt16*Lt13       kt18*Lt12         kt20*Lt12               (kt1*Lt16^2+kt10*Lt11^2+kt12*Lt11^2+kt14*Lt13^2+kt16*Lt13^2+kt18*Lt12^2+kt20*Lt12^2 )                 (kt10*Lt14*Lt11-kt12*Lt15*Lt11+kt14*Lt14*Lt13-kt16*Lt15*Lt13-kt18*Lt14*Lt12+kt20*Lt15*Lt12 )   kt1*Lt26*Lt16                                                                                                                  0                                                                                                                                             0                                                                               0                                                            ;
      (kt10*Lt14-kt12*Lt15+kt14*Lt14-kt16*Lt15+kt18*Lt14-kt20*Lt15 )                           0                                                                                    0                               0                               0                                 0                             -kt10*Lt14      kt12*Lt15          -kt14*Lt14       kt16*Lt15        -kt18*Lt14         kt20*Lt15               (kt10*Lt14*Lt11-kt12*Lt15*Lt11+kt14*Lt14*Lt13-kt16*Lt15*Lt13-kt18*Lt14*Lt12+kt20*Lt15*Lt12 )     (kt10*Lt14^2+kt12*Lt15^2+kt14*Lt14^2+kt16*Lt15^2+kt18*Lt14^2+kt20*Lt12^2 )                                             0                                                                                                                                               0                                                                                                                                            0                                                                               0                                                           ;
    kt1*Lt26                                                                                                                                   (-kt1*Lt26+(kt2+kt4+kt6+kt8 )*Lt21 )        -kt2*Lt21     -kt4*Lt21       -kt6*Lt21         -kt8*Lt21             0                                  0                                    0                                    0                                     0                                    0                                     (kt1*Lt16*Lt26 )                                                                                                                                                                          0                                                                                                                                                                                                 (kt1*Lt26^2+(kt2+kt4+kt6+kt8 )*Lt21^2 )                                             (kt2*Lt24*Lt21-kt4*Lt25*Lt21+kt6*Lt24*Lt21-kt8*Lt25*Lt21 )              (kt2*Lt23*Lt21-kt6*Lt22*Lt21 )                    (kt4*Lt23*Lt21-kt8*Lt22*Lt21 )  ;
             0                                                                                                                                                      (kt2*Lt24-kt4*Lt25+kt6*Lt24-kt8*Lt25 )   -kt2*Lt24    kt4*Lt25       -kt6*Lt24        kt8*Lt25             0                                  0                                    0                                    0                                     0                                    0                                            0                                                                                                                                                                                                         0                                                                                                                                                                                                 (kt2*Lt24*Lt21-kt4*Lt25*Lt21+kt6*Lt24*Lt21-kt8*Lt25*Lt21 )      (kt2*Lt24^2+kt4*Lt25^2+kt6*Lt24^2+kt8*Lt25^2 )                                     (kt2*Lt23*Lt24-kt6*Lt22*Lt24 )                    (-kt4*Lt23*Lt25+kt8*Lt22*Lt25 ) ;
             0                                                                                                                                                      (kt2*Lt23-kt6*Lt22 )                                        -kt2*Lt23        0                            kt6*Lt22           0                                   0                                  0                                    0                                    0                                     0                                    0                                            0                                                                                                                                                                                                         0                                                                                                                                                                                                  (kt2*Lt23*Lt21-kt6*Lt22*Lt21 )                                                                (kt2*Lt23*Lt24-kt6*Lt22*Lt24 )                                                                        (kt2*Lt23^2+kt6*Lt22^2 )                                        0                                                               ;
             0                                                                                                                                                      (kt4*Lt23-kt8*Lt22 )                                         0                             -kt4*Lt23         0                              kt8*Lt22             0                                  0                                    0                                    0                                     0                                    0                                            0                                                                                                                                                                                                         0                                                                                                                                                                                                  (kt4*Lt21*Lt23-kt8*Lt21*Lt22 )                                                                (-kt4*Lt23*Lt25+kt8*Lt22*Lt25 )                                                                                      0                                                                       (kt4*Lt23^2+kt8*Lt22^2 )              ];

Ct=[(ct1+ct10+ct12+ct14+ct16+ct18+ct20 )                                                                     -ct1                                                                            0                               0                               0                                 0                            -ct10                   -ct12                   -ct14                   -ct16                   -ct18                   -ct20                        (ct1*Lt16+ct10*Lt11+ct12*Lt11+ct14*Lt13+ct16*Lt13-ct18*Lt12-ct20*Lt12 )                                               (ct10*Lt14-ct12*Lt15+ct14*Lt14-ct16*Lt15+ct18*Lt14-ct20*Lt15 )                                                                ct1*Lt26                                                                                                                             0                                                                                                                                                0                                                                             0                                                             ;
      -(ct1 )                                                                                                                                       (ct1+ct2+ct4+ct6+ct8 )                                  -ct2                 -ct4                 -ct6                   -ct8                        0                                  0                                    0                                    0                                     0                                    0                                   -(ct1*Lt16 )                                                                                                                                                                                    0                                                                                                                                                                                                (-ct1*Lt26+(ct2+ct4+ct6+ct8 )*Lt21 )                                                     (ct2*Lt24-ct4*Lt25+ct6*Lt24-ct8*Lt25 )                                                       (ct2*Lt23-ct6*Lt22 )                                          (ct4*Lt23-ct8*Lt22 )                       ;
                0                                                                                                                                             -ct2                                                                             (ct2+ct3 )       0                               0                                 0                                   0                                  0                                    0                                    0                                     0                                    0                                              0                                                                                                                                                                                                      0                                                                                                                                                                                                -ct2*Lt21                                                                                                              -ct2*Lt24                                                                                                                     -ct2*Lt23                                                                        0                                                             ;
                0                                                                                                                                             -ct4                                                                             0                              (ct4+ct5 )        0                                 0                                   0                                  0                                    0                                    0                                     0                                    0                                              0                                                                                                                                                                                                      0                                                                                                                                                                                                -ct4*Lt21                                                                                                               ct4*Lt25                                                                                                                                    0                                                                       -ct4*Lt23                                              ;                             
                0                                                                                                                                             -ct6                                                                             0                               0                              (ct6+ct7 )          0                                   0                                  0                                    0                                    0                                     0                                    0                                              0                                                                                                                                                                                                      0                                                                                                                                                                                                -ct6*Lt21                                                                                                               -ct6*Lt24                                                                                                                    ct6*Lt22                                                                       0                                                             ;
                0                                                                                                                                             -ct8                                                                             0                               0                               0                                 (ct8+ct9 )           0                                  0                                    0                                    0                                     0                                    0                                              0                                                                                                                                                                                                      0                                                                                                                                                                                                -ct8*Lt21                                                                                                               ct8*Lt25                                                                                                                                    0                                                                       ct8*Lt22                                            ;
    -ct10                                                                                                                                                0                                                                                    0                               0                               0                                 0                             (ct10+ct11 )            0                                    0                                    0                                     0                                    0                                    -ct10*Lt11                                                                                                                                                                                 -ct10*Lt14                                                                                                                                                                                    0                                                                                                                                             0                                                                                                                                              0                                                                              0                                                             ;
    -ct12                                                                                                                                                0                                                                                    0                               0                               0                                 0                                   0                              (ct12+ct13 )            0                                    0                                     0                                    0                                    -ct12*Lt11                                                                                                                                                                                ct12*Lt15                                                                                                                                                                                    0                                                                                                                                             0                                                                                                                                              0                                                                              0                                                             ;
    -ct14                                                                                                                                                0                                                                                    0                               0                               0                                 0                                   0                                  0                                (ct14+ct15 )            0                                     0                                    0                                    -ct14*Lt13                                                                                                                                                                                 -ct14*Lt14                                                                                                                                                                                    0                                                                                                                                             0                                                                                                                                              0                                                                              0                                                             ;
    -ct16                                                                                                                                                0                                                                                    0                               0                               0                                 0                                   0                                  0                                    0                              (ct16+ct17 )             0                                    0                                    -ct16*Lt13                                                                                                                                                                                ct16*Lt15                                                                                                                                                                                    0                                                                                                                                              0                                                                                                                                             0                                                                              0                                                             ;    
    -ct18                                                                                                                                                0                                                                                    0                               0                               0                                 0                                   0                                  0                                    0                                    0                              (ct18+ct19 )             0                                    ct18*Lt12                                                                                                                                                                               -ct18*Lt14                                                                                                                                                                                     0                                                                                                                                              0                                                                                                                                             0                                                                              0                                                            ;                      
    -ct20                                                                                                                                                0                                                                                    0                               0                               0                                 0                                   0                                  0                                    0                                    0                                     0                               (ct20+ct21 )           ct20*Lt12                                                                                                                                                                               ct20*Lt15                                                                                                                                                                                    0                                                                                                                                              0                                                                                                                                             0                                                                               0                                                             ;
      (ct1*Lt16+ct10*Lt11+ct12*Lt11+ct14*Lt13+ct16*Lt13-ct18*Lt12-ct20*Lt12 )  -ct1*Lt16                                                                0                               0                               0                                 0                             -ct10*Lt11       -ct12*Lt11          -ct14*Lt13        -ct16*Lt13       ct18*Lt12         ct20*Lt12               (ct1*Lt16^2+ct10*Lt11^2+ct12*Lt11^2+ct14*Lt13^2+ct16*Lt13^2+ct18*Lt12^2+ct20*Lt12^2 )                 (ct10*Lt14*Lt11-ct12*Lt15*Lt11+ct14*Lt14*Lt13-ct16*Lt15*Lt13-ct18*Lt14*Lt12+ct20*Lt15*Lt12 )   ct1*Lt26*Lt16                                                                                                                  0                                                                                                                                             0                                                                               0                                                            ;
      (ct10*Lt14-ct12*Lt15+ct14*Lt14-ct16*Lt15+ct18*Lt14-ct20*Lt15 )                           0                                                                                    0                               0                               0                                 0                             -ct10*Lt14      ct12*Lt15          -ct14*Lt14       ct16*Lt15        -ct18*Lt14         ct20*Lt15               (ct10*Lt14*Lt11-ct12*Lt15*Lt11+ct14*Lt14*Lt13-ct16*Lt15*Lt13-ct18*Lt14*Lt12+ct20*Lt15*Lt12 )     (ct10*Lt14^2+ct12*Lt15^2+ct14*Lt14^2+ct16*Lt15^2+ct18*Lt14^2+ct20*Lt12^2 )                                             0                                                                                                                                               0                                                                                                                                            0                                                                               0                                                           ;
    ct1*Lt26                                                                                                                                   (-ct1*Lt26+(ct2+ct4+ct6+ct8 )*Lt21 )        -ct2*Lt21     -ct4*Lt21       -ct6*Lt21         -ct8*Lt21             0                                  0                                    0                                    0                                     0                                    0                                     (ct1*Lt16*Lt26 )                                                                                                                                                                          0                                                                                                                                                                                                 (ct1*Lt26^2+(ct2+ct4+ct6+ct8 )*Lt21^2 )                                             (ct2*Lt24*Lt21-ct4*Lt25*Lt21+ct6*Lt24*Lt21-ct8*Lt25*Lt21 )              (ct2*Lt23*Lt21-ct6*Lt22*Lt21 )                    (ct4*Lt23*Lt21-ct8*Lt22*Lt21 )  ;
             0                                                                                                                                                      (ct2*Lt24-ct4*Lt25+ct6*Lt24-ct8*Lt25 )   -ct2*Lt24    ct4*Lt25       -ct6*Lt24        ct8*Lt25             0                                  0                                    0                                    0                                     0                                    0                                            0                                                                                                                                                                                                         0                                                                                                                                                                                                 (ct2*Lt24*Lt21-ct4*Lt25*Lt21+ct6*Lt24*Lt21-ct8*Lt25*Lt21 )      (ct2*Lt24^2+ct4*Lt25^2+ct6*Lt24^2+ct8*Lt25^2 )                                     (ct2*Lt23*Lt24-ct6*Lt22*Lt24 )                    (-ct4*Lt23*Lt25+ct8*Lt22*Lt25 ) ;
             0                                                                                                                                                      (ct2*Lt23-ct6*Lt22 )                                        -ct2*Lt23        0                            ct6*Lt22           0                                   0                                  0                                    0                                    0                                     0                                    0                                            0                                                                                                                                                                                                         0                                                                                                                                                                                                  (ct2*Lt23*Lt21-ct6*Lt22*Lt21 )                                                                (ct2*Lt23*Lt24-ct6*Lt22*Lt24 )                                                                        (ct2*Lt23^2+ct6*Lt22^2 )                                        0                                                               ;
             0                                                                                                                                                      (ct4*Lt23-ct8*Lt22 )                                         0                             -ct4*Lt23         0                              ct8*Lt22             0                                  0                                    0                                    0                                     0                                    0                                            0                                                                                                                                                                                                         0                                                                                                                                                                                                  (ct4*Lt21*Lt23-ct8*Lt21*Lt22 )                                                                (-ct4*Lt23*Lt25+ct8*Lt22*Lt25 )                                                                                      0                                                                       (ct4*Lt23^2+ct8*Lt22^2 )              ];
         
         
         
         At=[zeros(18) eye(18);
                -Mt^-1*Kt  -Mt^-1*Ct];
            
        Bt=zeros(36,10);
        Bt(21,1)=kt3/mt3;
        Bt(22,2)=kt5/mt4;
        Bt(23,3)=kt7/mt5;
        Bt(24,4)=kt9/mt6;
        Bt(25,5)=kt11/mt7;
        Bt(26,6)=kt13/mt8;
        Bt(27,7)=kt15/mt9;
        Bt(28,8)=kt17/mt10;
        Bt(29,9)=kt19/mt11;
        Bt(30,10)=kt21/mt12;
        
        
        CCt=[zeros(2,36)];
        CCt(1,1)=1;
        CCt(2,2)=1;
        
%         CCt=[eye(18) zeros(18)];
        Dt=zeros(2,10);
        
    
    